FROM golang:1.13.4-alpine AS build

WORKDIR /home/xtreme/go/src/gitlab.com/kubecronjob
COPY main.go go.* /home/xtreme/go/src/gitlab.com/kubecronjob
RUN CGO_ENABLED=0 go build -o /bin/demo

FROM scratch
COPY --from=build /bin/demo /bin/demo
ENTRYPOINT ["/bin/demo"]
